### ISSUE TITLE
Casting Proxer.Me Player

### ISSUE THREAD

**Issue by otakupasi** [proxer/ProxerAndroid#23]
There seems to be a issue with the cast button within the Proxer.Me Player.

Some Streams do not offer a cast button even though
1) The phone is connected to the local Wifi
2) The cast device is up and running in the same Wifi
3) The stream is hosted on a Proxer.Me Server

I tested multiple Episodes of given Animes and could only find that stream. (Other streams of Fukumenkei Noise run on another server/subdomain)

Hope you can fix this Bug soon.

Example: 
- NoCastButton:  
  - Fukumenkei Noise Ep. 1 Eng Sub 
  Running on: https://s69.ps.proxer.me/files/7/...
- HasCastButton:
  - Bleach Ep. 204 Eng Sub
   Running on https://s14-ps.proxer.me/files/4/...

App-Version: 1.6.2
Device(Smartphone):
HUAWEI VNS-L31
Running on Android 7.0 with EMUI 5.0.4
Not-Rooted

Cast-Device(Chromecast):
Google Chromecast Second Generation
Firmware-Version: 1.32.141268

Wifi-Information:
Download-Speed: 39.2
Upload-Speed: 5.64
Latency: 20ms
Number of Devices: 7

**Comment by rubengees** [comment]
Thanks for the detailed bug report! Will look into it shortly.

**Comment by rubengees** [comment]
This should be fixed in the commit above. You can try [this version](https://github.com/proxer/ProxerAndroid/files/2849478/app-1.6.3-release.zip) with that change (it's the same build as the one uploaded to the play store).

If it's not working, please reopen the issue, thanks! :slightly_smiling_face:
